#!/bin/bash

if [ ! -f index.php && -f index.html ]
then mv index.html index.php
fi

git add *

if [ -z $1 ]
then MSG="..."
else MSG=$1
fi

git commit -a --m $MSG
git push heroku master
mv index.php index.html